[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
selff = "Ei59ErEipxrfh6bJkdXNHFxyE2YKsbpcj1ZQfBFHTWY6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/hamdan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
